### ISSUE TITLE
some dependencies are not present in pom.xml

### ISSUE THREAD

**Issue by shubhamgupta3025** [IATA-Cargo/one-record-server-java#22]
While building the project, there was errors before adding these dependencies.
![image](https://user-images.githubusercontent.com/32764576/125431073-97e0440f-1eca-47df-bf63-9832a19f2f0e.png)

I want to deploy one record, Is there something I am missing? Please let me know if there is a better solution. 

![image](https://user-images.githubusercontent.com/32764576/125439018-3d43c05e-430a-420e-8f30-6aa3ab890216.png)

**Comment by IATA-Cargo** [comment]
The jopa version was outdated and caused the error. Now updated.
