### ISSUE TITLE
Missing IATA-1R-API-Ontology.ttl

### ISSUE THREAD

**Issue by lzcapp** [IATA-Cargo/one-record-server-java#38]
When excuting the command: `mvn -Djdk.tls.client.protocols=TLSv1.2 exec:java`, It reports the error:

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project one-record-server-java: An exception occured while executing the Java class. Read timed out -> [Help 1]
```

![Snipaste_2024-05-17_11-36-15](https://github.com/IATA-Cargo/one-record-server-java/assets/12462465/793e40e2-fd11-4e14-92b6-4d1adf0686e1)

**Comment by IATA-Cargo** [comment]
Dear @lzcapp,
the ONE Record java server is discontinued. 
Instead, you can use NE:ONE, here the guide to setup a local environment: https://github.com/IATA-Cargo/one-record-first-steps
Best,
Davide

**Comment by lzcapp** [comment]
@IATA-Cargo Thanks for the response!

Yes, we have turned to the ne:one project. And BTW you should set this repo to be `Archived`.

Thanks again and wish you a nice day!

**Comment by IATA-Cargo** [comment]
@lzcapp thanks a lot for your suggestion, we are going to discuss about it.
