### ISSUE TITLE
Install Problems

### ISSUE THREAD

**Issue by stevedevchap** [IATA-Cargo/one-record-server-java#5]
Hi There, 

I am following the installation instructions on my test rig and am experiencing problems at the mvn exec:java stage. I am receiving ClassNotFoundException: org.iata.util.GithubUtil. It appears to be on executing the goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java.

My test rig is 
Windows 10, version: 10.0, arch: amd64
Apache Maven 3.6.3
Java version: 1.8.0_151, vendor Oracle Corporation

Would you be able to advise?

**Comment by andrablaj** [comment]
Hi! Thank you for raising the issue. Have you tried to execute `mvn clean install` before the `mvn exec:java`? I might have mixed up steps 2 and 3 in the `readme `file.
